catalog
catalogChangeLog

^ '
- Version 2.3 - 2013-11-22 Monty''s Enhancements
[[[ 
	(ConfigurationOfXMLWriter project version: ''2.3'') load
]]]

- Version 2.2.1 - 2013-07-10 Merged fix of Camillo for fileSystem interaction.
[[[ 
	(ConfigurationOfXMLWriter project version: ''2.2.1'') load
]]]

- Version 2.2.0 - Migrated to PharoExtras
[[[ 	
	(ConfigurationOfXMLWriter project version: ''2.2.0'') load
]]]
	
- Version 2.1.0 Introduced tests and symbolic configurations
[[[ 
	(ConfigurationOfXMLWriter project version: ''2.1.0'') load
	(ConfigurationOfXMLWriter project version: ''2.1.0'') record loadDirective
]]]

- Version 2.0.0 After SmalltalkHub Migration and the introduction of configuration in other projects
- Pre-smalltalkhub migration
[[[
	(ConfigurationOfXMLWriter project version: ''1.0.5'') load
]]]
'